### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by Thirumalaimurugan** [IONISx/edx-theme#35]
sudo npm install -g grunt-cli bower is sucess after that I tried the following and I got the error

sudo npm install 

sudo npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/test/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/test
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! path /home/test/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/test/npm-debug.log
npm ERR! not ok code 0

**Comment by tusbar** [comment]
You need to be in the theme’s directory in order to run `npm install`.

    cd edx-theme
    npm install
