### ISSUE TITLE
Two Pipeline problems

### ISSUE THREAD

**Issue by echanna** [IONISx/edx-theme#36]
At times I get this:

ValueError: The file 'themes/ionisx/images/spinner.gif' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x50adbd0>.

ValueError: The file 'themes/ionisx/fonts/font-awesome/fontawesome-webfont.woff2' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x5010f90>.

How do I solve this problem?

**Comment by echanna** [comment]
I think I found out why, had to do with how I was trying to re-locate resources.  For now I think I have resolved this

**Comment by tusbar** [comment]
Make sure you use `ionisx` as `THEME_NAME` in the settings if you’re using paths like those.

**Comment by echanna** [comment]
Hi Bertrand,


Thanks for your reply.  I notice that while switching between the IONISX theme and lets the custom theme that I work on, after rebuilding the assets manually, and restarting the workers for edx, the theme switch is not complete.  For example there are remnants of the IONISX theme in the theme that I am switching to.  The other theme has no relation.  I followed these best practices:


Compile assets manually

To compile javascript and css outside of the update script run the following commands:

sudo -H -u edxapp bash
source /edx/app/edxapp/edxapp_env
cd /edx/app/edxapp/edx-platform
paver update_assets cms --settings=aws
paver update_assets lms --settings=aws?

Restarting Services

LMS/CMS - sudo /edx/bin/supervisorctl -c /edx/etc/supervisord.conf restart edxapp:
Workers - sudo /edx/bin/supervisorctl -c /edx/etc/supervisord.conf restart edxapp_worker:
(Note: the colon character : at the end of the line is mandatory!)




Thanks,
Edward Hanna
________________________________
