### ISSUE TITLE
Error at grunt build

### ISSUE THREAD

**Issue by brenthmiras** [IONISx/edx-theme#37]
Running "less:theme" (less) task
>> FileError: 'bootstrap/less/bootstrap.less' wasn't found in static/less/main.less on line 1, column 1:
>> 1 @import 'bootstrap/less/bootstrap.less';
>> 2 @import 'font-awesome/less/font-awesome.less';

It's clearly an import error. because the bootstrap folder was not found.
I run a find for that bootstrap folder but it really does not exist.
Where did I go wrong?

**Comment by tusbar** [comment]
You did not `bower install`.

**Comment by brenthmiras** [comment]
I did. It's just that It didnt execute because I'm on sudo.
