### ISSUE TITLE
Stuck at Running "watch" task Waiting...

### ISSUE THREAD

**Issue by brenthmiras** [IONISx/edx-theme#38]
It got stuck at Running "watch" task Waiting... when running grunt build.

**Comment by tusbar** [comment]
It is very unlikely, as the `build` task [does not watch](https://github.com/IONISx/edx-theme/blob/master/Gruntfile.js#L145).

**Comment by brenthmiras** [comment]
It's happens when running grunt not grunt build Im sorry.

**Comment by tusbar** [comment]
Well that is the expected behavior.

The `grunt watch` task watches for file changes.
