### ISSUE TITLE
IONISx theme installed but doesn't take effect

### ISSUE THREAD

**Issue by elimence** [IONISx/edx-theme#47]
I've successfully installed the ionisx theme, but it doesn't change the lms ui.
I'd previously installed the stanford theme, and that's what's still showing.
I'm I missing something?

**Comment by tusbar** [comment]
@elimence you need to restart the devstack (without the --fast switch).

If you’re not using the devstack – you need to run `paver update_assets --settings <your-settings>`.

**Comment by elimence** [comment]
@tusbar I'm running edx on an ubuntu server.
I've got it running now though.
Initially I just clone the repo and used it as-is, but then I just did an npm install, bower install, then built with grunt and the pushing to github before running the update.
All seems to be in order now.
:)

**Comment by tusbar** [comment]
@elimence as said on the README, you should not npm install nor bower install to get the theme work.

This should only be done in a development environment.

The built assets are committed in the repository, so if you want to customize the theme – fork it, update it, build the assets using `grunt build` and commit them in.
