### ISSUE TITLE
IONISX Theme on Cypress

### ISSUE THREAD

**Issue by sbalde** [IONISx/edx-theme#48]
Hello,

@tusbar 
Is there any way to make this theme work on Cypress (the new version of EDX)?

regards,

**Comment by tusbar** [comment]
Hey @sbalde,

@mtyaka has been working to get the theme compatible on Cypress – so the `master` branch should be compatible. (See #46).

I have not tested it yet but I will very soon. In the meanwhile, you should try that and tell me if there’s anything wrong.

**Comment by sbalde** [comment]
Thanks @tusbar for your answer;

I started working on it yesterday but i had an issue while processing "nmp install".

I'll continu the work this evening and let you know i finally get to the end or not

**Comment by sbalde** [comment]
Hello Guys @tusbar @mtyaka 

I'm trying to set up the Ionisx theme on cypress unfortunately, I'm facing an issue whenever i try to update the lms assets.
Here below the output of the command.

vagrant@precise64:~$ sudo -H -u edxapp bash
edxapp@precise64:~/edx-platform$ source /edx/app/edxapp/edxapp_env 
edxapp@precise64:~/edx-platform$ cd /edx/app/edxapp/edx-platform/
edxapp@precise64:~/edx-platform$ paver update_assets lms --settings=aws
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
Ruby prereqs unchanged, skipping...
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
python manage.py lms --settings=aws preprocess_assets
2015-08-24 20:30:47,397 INFO 5755 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common /edx/app/edxapp/themes/guandhal -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path /edx/app/edxapp/themes/guandhal/static/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css /edx/app/edxapp/themes/guandhal/static/sass cms/static/sass:cms/static/css common/static/sass:common/static/css


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common /edx/app/edxapp/themes/guandhal -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path /edx/app/edxapp/themes/guandhal/static/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css /edx/app/edxapp/themes/guandhal/static/sass cms/static/sass:cms/static/css common/static/sass:common/static/css

Build failed running pavelib.assets.update_assets: Subprocess return code: 1

Have you ever had a similar issue or do you have any idea about how to overcome this?

PS: i renamed the "Ionisx" theme directory to "guandhal" et setted up the lms.env.json

Thanks in advance for your time.

Regards,

**Comment by tusbar** [comment]
@sbalde if you want to rename the theme you also need to rename this file: https://github.com/IONISx/edx-theme/blob/master/static/sass/_ionisx.scss to match your theme name.

**Comment by sbalde** [comment]
@tusbar thank you very much, i used to rename the .scss but unfortunately i forgot this time. Maybe I was tired.
It's now working as well.
Thank you again.
Have a nice day ;)

**Comment by tusbar** [comment]
@sbalde no problem! don’t hesitate to open a pull request if you see anything looking odd. :)
